#!/usr/bin/env python

from pprint import pprint

info = """
{'id': 4, 'url': 'https://netbox.lasthop.io/api/dcim/devices/4/', 'display': 'arista4', 'name': 'arista4', 'device_type': {'id': 2, 'url': 'https://netbox.lasthop.io/api/dcim/device-types/2/', 'display': 'vEOS', 'manufacturer': {'id': 2, 'url': 'https://netbox.lasthop.io/api/dcim/manufacturers/2/', 'display': 'Arista', 'name': 'Arista', 'slug': 'arista'}, 'model': 'vEOS', 'slug': 'arista-veos'}, 'role': {'id': 4, 'url': 'https://netbox.lasthop.io/api/dcim/device-roles/4/', 'display': 'Distribution Switch', 'name': 'Distribution Switch', 'slug': 'distribution-switch'}, 'device_role': {'id': 4, 'url': 'https://netbox.lasthop.io/api/dcim/device-roles/4/', 'display': 'Distribution Switch', 'name': 'Distribution Switch', 'slug': 'distribution-switch'}, 'tenant': None, 'platform': None, 'serial': '', 'asset_tag': None, 'site': {'id': 2, 'url': 'https://netbox.lasthop.io/api/dcim/sites/2/', 'display': 'Fremont Data Center', 'name': 'Fremont Data Center', 'slug': 'fremont-dc'}, 'location': None, 'rack': {'id': 1, 'url': 'https://netbox.lasthop.io/api/dcim/racks/1/', 'display': 'RK1', 'name': 'RK1'}, 'position': None, 'face': None, 'latitude': None, 'longitude': None, 'parent_device': None, 'status': {'value': 'active', 'label': 'Active'}, 'airflow': None, 'primary_ip': None, 'primary_ip4': None, 'primary_ip6': None, 'oob_ip': None, 'cluster': None, 'virtual_chassis': None, 'vc_position': None, 'vc_priority': None, 'description': '', 'comments': '', 'config_template': None, 'config_context': {}, 'local_context_data': None, 'tags': [], 'custom_fields': {}, 'created': '2023-11-28T20:11:25.213903Z', 'last_updated': '2023-11-28T20:11:25.213924Z', 'console_port_count': 0, 'console_server_port_count': 0, 'power_port_count': 0, 'power_outlet_count': 0, 'interface_count': 0, 'front_port_count': 0, 'rear_port_count': 0, 'device_bay_count': 0, 'module_bay_count': 0, 'inventory_item_count': 0}
"""

pprint(info)
